const footerItems = [
    'O NÁS',
    'BLOG',
    'INSTAGRAM',
    'FACEBOOK',
    'KONTAKT',
    'SPOLUPRÁCE',
    'ČLENSTVÍ'
  ];
  
 

  const footerConditions = [
    "Obchodní podmínky",
    "Ochrana osobních údajů",
    "Cookies"
  ];


 export const countryNames = [
    'Francie',
    'Španělsko',
    'Spojené státy',
    'Čína',
    'Itálie',
    'Mexiko',
    'Velká Británie',
    'Turecko',
    'Německo',
    'Thajsko',
    'Rakousko',
    'Řecko',
    'Japonsko',
    'Malajsie',
    'Rusko',
    'Portugalsko',
    'Kanada',
    'Saúdská Arábie',
    'Jižní Korea',
    'Austrálie',
    'Nizozemsko',
    'Egypt',
    'Indie',
    'Vietnam',
    'Indonésie',
    'Švýcarsko',
    'Argentina',
    'Švédsko',
    'Polsko',
    'Česká republika',
    'Belgie',
    'Norsko',
    'Dánsko',
    'Singapur',
    'Finsko',
    'Maroko',
    'Brazílie',
    'Spojené arabské emiráty',
    'Irsko',
    'Maďarsko',
    'Izrael',
    'Filipíny',
    'Chile',
    'Nový Zéland',
    'Jižní Afrika',
    'Peru',
    'Rumunsko',
    'Chorvatsko',
    'Keňa',
    'Srí Lanka',
    'Írán',
    'Kolumbie',
    'Hongkong',
    'Tanzanie',
    'Ukrajina',
    'Bulharsko',
    'Srbsko',
    'Katar',
    'Lucembursko',
    'Slovensko',
    'Lotyšsko',
    'Litva',
    'Estonsko',
    'Bahrajn',
    'Kypr',
    'Malta',
    'Černá Hora',
    'Omán',
    'Panama',
    'Arménie',
    'Bosna a Hercegovina',
    'Jordánsko',
    'Gruzie',
    'Albánie',
    'Mauricius',
    'Kuvajt',
    'Libanon',
    'Kostarika',
    'Uruguay',
    'Kazachstán',
    'Bolívie',
    'Guatemala',
    'Ekvádor',
    'Island',
    'Makedonie',
    'Nepál',
    'Paraguay',
    'Zimbabwe',
    'Ghana',
    'Ázerbájdžán',
    'Zambie',
    'Honduras',
    'Jamajka',
    'Etiopie',
    'Kamerun',
    'Madagaskar',
    'Kuba',
    'Dominikánska republika',
    'Tunisko',
  ];


  export const popularCountryNames = [
    'Chorvatsko',
    'Itálie',
    'Rakousko',
    'Španělsko',
    'Řecko',
    'Turecko',
    'Francie',
    'Německo',
    'Thajsko',
    'Spojené arabské emiráty',
    'Egypt',
    'Bulharsko',
    'Velká Británie',
    'Portugalsko',
    'Maďarsko',
    'Švýcarsko',
    'Indie',
    'Kuba'
  ];
  
  export const countriesData = [
    {
      name: 'Francie',
      population: '67,1 milionu',
      currency: 'Euro (EUR)',
      language: 'Francouzština',
      capital: 'Paříž',
      area: '551 695 km²',
      timezone: 'UTC+1 až UTC+2',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg',
 
    },
    {
      name: 'Španělsko',
      population: '47,3 milionu',
      currency: 'Euro (EUR)',
      language: 'Španělština',
      capital: 'Madrid',
      area: '505 990 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg',
 
    },
    {
      name: 'Spojené státy',
      population: '331 milionů',
      currency: 'Dolar (USD)',
      language: 'Angličtina',
      capital: 'Washington, D.C.',
      area: '9,83 milionu km²',
      timezone: 'UTC−4 až UTC−12, +10, +11',
      continent: 'Severní Amerika',
      flag: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg',
   
    },
    {
      name: 'Itálie',
      population: '60,4 milionu',
      currency: 'Euro (EUR)',
      language: 'Italština',
      capital: 'Řím',
      area: '301 340 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg',
 
    },
    {
      name: 'Čína',
      population: '1,41 miliardy',
      currency: 'Juan (CNY)',
      language: 'Čínština',
      capital: 'Peking',
      area: '9,597 milionu km²',
      timezone: 'UTC+8',
      continent: 'Asie',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg',

    },
    {
      name: 'Velká Británie',
      population: '67,1 milionu',
      currency: 'Libra (GBP)',
      language: 'Angličtina',
      capital: 'Londýn',
      area: '242 495 km²',
      timezone: 'UTC+0',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    
    },
    {
      name: 'Mexiko',
      population: '126 milionů',
      currency: 'Mexické peso (MXN)',
      language: 'Španělština',
      capital: 'Mexiko mesto',
      area: '1,96 milionu km²',
      timezone: 'UTC−8 až UTC−5',
      continent: 'Severní Amerika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg',
  
    },
    {
      name: 'Kanada',
      population: '37,7 milionu',
      currency: 'Kanadský dolar (CAD)',
      language: 'Angličtina, Francouzština',
      capital: 'Ottawa',
      area: '9,98 milionu km²',
      timezone: 'UTC−3.5 až UTC−8',
      continent: 'Severní Amerika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg',
  
    },
    {
      name: 'Turecko',
      population: '84,3 milionu',
      currency: 'Turecká lira (TRY)',
      language: 'Turečtina',
      capital: 'Ankara',
      area: '783 356 km²',
      timezone: 'UTC+3',
      continent: 'Asie',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg',

    },
    {
      name: 'Německo',
      population: '83,2 milionu',
      currency: 'Euro (EUR)',
      language: 'Němčina',
      capital: 'Berlín',
      area: '357 022 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
    
    },
    {
      name: 'Japonsko',
      population: '126 milionů',
      currency: 'Japonský jen (JPY)',
      language: 'Japonština',
      capital: 'Tokio',
      area: '377 975 km²',
      timezone: 'UTC+9',
      continent: 'Asie',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg',

    },{
      name: 'Thajsko',
      population: '69,8 milionu',
      currency: 'Thajský baht (THB)',
      language: 'Thajština',
      capital: 'Bangkok',
      area: '513 120 km²',
      timezone: 'UTC+7',
      continent: 'Asie',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg',

    },
    {
      name: 'Spojené arabské emiráty',
      population: '9,89 milionu',
      currency: 'Dirham (AED)',
      language: 'Arabština',
      capital: 'Abú Zabí',
      area: '83 600 km²',
      timezone: 'UTC+4',
      continent: 'Asie',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg',
   
    },
    {
      name: 'Egypt',
      population: '104 milionů',
      currency: 'Egyptská libra (EGP)',
      language: 'Egyptština',
      capital: 'Káhira',
      area: '1 010 408 km²',
      timezone: 'UTC+2',
      continent: 'Afrika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg',

    },
    {
      name: 'Bulharsko',
      population: '6,92 milionu',
      currency: 'Bulharský lev (BGN)',
      language: 'Bulharština',
      capital: 'Sofie',
      area: '110 879 km²',
      timezone: 'UTC+2',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg',
   
    },
    {
      name: 'Portugalsko',
      population: '10,3 milionu',
      currency: 'Euro (EUR)',
      language: 'Portugalština',
      capital: 'Lisabon',
      area: '92 212 km²',
      timezone: 'UTC+0',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',

    },
 
    {
      name: 'Dominikánska republika',
      population: '10,9 milionu',
      currency: 'Dominikánské peso (DOP)',
      language: 'Španělština',
      capital: 'Santo Domingo',
      area: '48 671 km²',
      timezone: 'UTC-4',
      continent: 'Severní Amerika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg',

    },
    {
      name: 'Tunisko',
      population: '11,7 milionu',
      currency: 'Tuniský dinár (TND)',
      language: 'Arabština',
      capital: 'Tunis',
      area: '163 610 km²',
      timezone: 'UTC+1',
      continent: 'Afrika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg',
 
    },
    {
      name: 'Maďarsko',
      population: '9,7 milionu',
      currency: 'Maďarský forint (HUF)',
      language: 'Maďarština',
      capital: 'Budapešť',
      area: '93 030 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg',
    
    },
    {
      name: 'Švýcarsko',
      population: '8,6 milionu',
      currency: 'Švýcarský frank (CHF)',
      language: 'Němčina, Francouzština, Italština, Romanština',
      capital: 'Bern',
      area: '41 290 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg',

    },{
      name: 'Chorvatsko',
      population: '4,07 milionu',
      currency: 'Chorvatská kuna (HRK)',
      language: 'Chorvatština',
      capital: 'Záhřeb',
      area: '56 594 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg',
    },
    {
      name: 'Řecko',
      population: '10,4 milionu',
      currency: 'Euro (EUR)',
      language: 'Řečtina',
      capital: 'Atény',
      area: '131 957 km²',
      timezone: 'UTC+2',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg',
    },
    {
      name: 'Rakousko',
      population: '8,9 milionu',
      currency: 'Euro (EUR)',
      language: 'Němčina',
      capital: 'Vídeň',
      area: '83 879 km²',
      timezone: 'UTC+1',
      continent: 'Evropa',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
    },
    {
      name: 'Indie',
      population: '1,366 miliard',
      currency: 'Indická rupie (INR)',
      language: 'Hindština, Angličtina a 21 dalších jazyků',
      capital: 'Nové Dillí',
      area: '3,287,263 km²',
      timezone: 'UTC+05:30',
      continent: 'Asie',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_India.svg',
    },
    {
      name: 'Kuba',
      population: '11,3 milionu',
      currency: 'Kubánské peso (CUP)',
      language: 'Španělština',
      capital: 'Havana',
      area: '109 884 km²',
      timezone: 'UTC-5 až UTC-4',
      continent: 'Severní Amerika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg',
  },
  {
      name: 'Kolumbie',
      population: '50,9 milionu',
      currency: 'Kolumbijské peso (COP)',
      language: 'Španělština',
      capital: 'Bogotá',
      area: '1 141 748 km²',
      timezone: 'UTC-5',
      continent: 'Jižní Amerika',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg',
  }
    
    
  ]
  

  export const typeOfTour = [
    'Pohoda u moře',
    'Přírodní tour',
    'Túry po horách',
    'Večírky a party',
    'Kulturní tour',
    'Dobrodružné tour',
    'Vinařské tour',
    'Gastro tour',
    'Fotografické tour',
    'Wellness pobyty',
    'Edukativní tour',
    'Sportovní tour',
    'Dobrovolnické tour'
  ];
  

  

  export const countryNamesObjects = [
    { value: 'Francie', label: 'Francie' },
    { value: 'Španělsko', label: 'Španělsko' },
    { value: 'Spojené státy', label: 'Spojené státy' },
    { value: 'Čína', label: 'Čína' },
    { value: 'Itálie', label: 'Itálie' },
    { value: 'Mexiko', label: 'Mexiko' },
    { value: 'Spojené království', label: 'Spojené království' },
    { value: 'Turecko', label: 'Turecko' },
    { value: 'Německo', label: 'Německo' },
    { value: 'Thajsko', label: 'Thajsko' },
    { value: 'Rakousko', label: 'Rakousko' },
    { value: 'Řecko', label: 'Řecko' },
    { value: 'Japonsko', label: 'Japonsko' },
    { value: 'Malajsie', label: 'Malajsie' },
    { value: 'Rusko', label: 'Rusko' },
    { value: 'Portugalsko', label: 'Portugalsko' },
    { value: 'Kanada', label: 'Kanada' },
    { value: 'Saúdská Arábie', label: 'Saúdská Arábie' },
    { value: 'Jižní Korea', label: 'Jižní Korea' },
    { value: 'Austrálie', label: 'Austrálie' },
    { value: 'Nizozemsko', label: 'Nizozemsko' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'Indie', label: 'Indie' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Indonésie', label: 'Indonésie' },
    { value: 'Švýcarsko', label: 'Švýcarsko' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Švédsko', label: 'Švédsko' },
    { value: 'Polsko', label: 'Polsko' },
    { value: 'Česká republika', label: 'Česká republika' },
    { value: 'Belgie', label: 'Belgie' },
    { value: 'Norsko', label: 'Norsko' },
    { value: 'Dánsko', label: 'Dánsko' },
    { value: 'Singapur', label: 'Singapur' },
    { value: 'Finsko', label: 'Finsko' },
    { value: 'Maroko', label: 'Maroko' },
    { value: 'Brazílie', label: 'Brazílie' },
    { value: 'Spojené arabské emiráty', label: 'Spojené arabské emiráty' },
    { value: 'Irsko', label: 'Irsko' },
    { value: 'Maďarsko', label: 'Maďarsko' },
    { value: 'Izrael', label: 'Izrael' },
    { value: 'Filipíny', label: 'Filipíny' },
    { value: 'Chile', label: 'Chile' },
    { value: 'Nový Zéland', label: 'Nový Zéland' },
    { value: 'Jižní Afrika', label: 'Jižní Afrika' },
    { value: 'Peru', label: 'Peru' },
    { value: 'Rumunsko', label: 'Rumunsko' },
    { value: 'Chorvatsko', label: 'Chorvatsko' },
    { value: 'Keňa', label: 'Keňa' },
    { value: 'Srí Lanka', label: 'Srí Lanka' },
    { value: 'Írán', label: 'Írán' },
    { value: 'Kolumbie', label: 'Kolumbie' },
    { value: 'Hongkong', label: 'Hongkong' },
    { value: 'Tanzanie', label: 'Tanzanie' },
    { value: 'Ukrajina', label: 'Ukrajina' },
    { value: 'Bulharsko', label: 'Bulharsko' },
    { value: 'Srbsko', label: 'Srbsko' },
    { value: 'Katar', label: 'Katar' },
    { value: 'Lucembursko', label: 'Lucembursko' },
    { value: 'Slovensko', label: 'Slovensko' },
    { value: 'Lotyšsko', label: 'Lotyšsko' },
    { value: 'Litva', label: 'Litva' },
    { value: 'Estonsko', label: 'Estonsko' },
    { value: 'Bahrajn', label: 'Bahrajn' },
    { value: 'Kypr', label: 'Kypr' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Černá Hora', label: 'Černá Hora' },
    { value: 'Omán', label: 'Omán' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Arménie', label: 'Arménie' },
    { value: 'Bosna a Hercegovina', label: 'Bosna a Hercegovina' },
    { value: 'Jordánsko', label: 'Jordánsko' },
    { value: 'Gruzie', label: 'Gruzie' },
    { value: 'Albánie', label: 'Albánie' },
    { value: 'Mauricius', label: 'Mauricius' },
    { value: 'Kuvajt', label: 'Kuvajt' },
    { value: 'Libanon', label: 'Libanon' },
    { value: 'Kostarika', label: 'Kostarika' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Kazachstán', label: 'Kazachstán' },
    { value: 'Bolívie', label: 'Bolívie' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Ekvádor', label: 'Ekvádor' },
    { value: 'Island', label: 'Island' },
    { value: 'Makedonie', label: 'Makedonie' },
    { value: 'Nepál', label: 'Nepál' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Zimbabwe', label: 'Zimbabwe' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Ázerbájdžán', label: 'Ázerbájdžán' },
    { value: 'Zambie', label: 'Zambie' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Jamajka', label: 'Jamajka' },
    { value: 'Etiopie', label: 'Etiopie' },
    { value: 'Kamerun', label: 'Kamerun' },
    { value: 'Madagaskar', label: 'Madagaskar' },
    { value: 'Kuba', label: 'Kuba' }
    ];

  export const typeOfTourObjects = [
      { value: 'Pohoda u moře', label: 'Pohoda u moře' },
      { value: 'Přírodní tour', label: 'Přírodní tour' },
      { value: 'Túry po horách', label: 'Túry po horách' },
      { value: 'Večírky a party', label: 'Večírky a party' },
      { value: 'Kulturní tour', label: 'Kulturní tour' },
      { value: 'Dobrodružné tour', label: 'Dobrodružné tour' },
      { value: 'Vinařské tour', label: 'Vinařské tour' },
      { value: 'Gastro tour', label: 'Gastro tour' },
      { value: 'Fotografické tour', label: 'Fotografické tour' },
      { value: 'Wellness pobyty', label: 'Wellness pobyty' },
      { value: 'Edukativní tour', label: 'Edukativní tour' },
      { value: 'Sportovní tour', label: 'Sportovní tour' },
      { value: 'Dobrovolnické tour', label: 'Dobrovolnické tour' }
  ];
  